### ISSUE TITLE
Options to disable Ip fallback when determine machine id

### ISSUE THREAD

**Issue by HigherOrderLogic** [houseme/snowflake-rs#13]
As the title said, I want the option to disable fallback to getting Ip as machine code.

https://github.com/houseme/snowflake-rs/blob/64e015cbb05881e0d03c2c616693c5d438bb11ba/src/builder.rs#L114-L116

For example:
 ```toml
 [features]
default = []
ip-fallback = ["dep:pnet_datalink"]
```

The reason is because compiling `pnet` on Windows [require some setup](https://github.com/libpnet/libpnet#windows) and maybe someone (like me) opt to choose the less of a hassle way of just not wanting it.
